# Generated by Django 6.0.2 on 2026-02-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.CharField(max_length=255, unique=True)),
                ('frequency', models.PositiveIntegerField(default=1, help_text='How often this query led to a match')),
                ('last_searched', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-frequency', '-last_searched'],
            },
        ),
    ]
